## Project-wide Gradle settings.

# JVM arguments for the daemon process
org.gradle.jvmargs=-Xms256m -Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Allow this legacy Android Gradle Plugin to build from the current Chinese path.
android.overridePathCheck=true
